# Site settings
baseurl: ''
url: 'https://www.realestate.if.ua'
dimain: realestate.if.ua

encoding: UTF-8
lang: uk_UA
timezone: Europe/Kyiv
country: Україна
region: Івано-Франківська область

usd: 27.50
eur: 32.50

title: Мережа вебсайтів нерухомості
keywords: нерухомість, квартира, будинок, кімната, гараж, майно, приміщення, власність, продаємо, здається, будівля, продаж, оренда, подобово, послуги, купити, продати, знайти, житло, нежитлове, продамо, земля, ділянка, оголошення, продаю, власник, магазин, склад, новобудова, продається, здаю, безкоштовно
description: База даних квартир, будинків, землі та багато інших об'єктів нерухомого майна, які будуються, продаються або передаються в оренду в Івано-Франківськ області.
name: Регіональна нерухомість
brand: Нерухомість
logo: "/assets/images/logo.svg"

author:
  name: Vasyl&nbsp;Mosiychuk
  website: http://www.vasyl.net
  email: info@vasyl.net
developer:
  name: vasyl.net
  website: http://www.vasyl.net
  email: info@vasyl.net

contact:
  name: Мережа вебсайтів нерухомості в&nbsp;України
  address: 76018, м. Івано-Франківськ, вул.&nbsp;Січових&nbsp;Стрільців,&nbsp;56
  phone_main: 380674330066
  phone_hot: 380674330066
  phone_fax: 380674330066
  phone_sms: 380674330066
  email: info@realestate.if.ua
  www: https://www.realestate.if.ua/

markdown: kramdown
kramdown:
  auto_ids: false

collections:
  stabs:
    output: true
  otabs:
    output: true
  owners:
    output: true

defaults:
  - scope:
      path: /*/data/*.json
    values:
      layout: "null"
      sitemap: false
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: /*/news/
      type: "news"
    values:
      layout: "news"
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2

sass:
  style: compressed

compress_html:
  clippings: all
  comments: [""]
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]
