# Site settings
baseurl: ''
domain: realestate.if.ua
url: 'https://www.realestate.if.ua'

encoding: UTF-8
lang: uk_UA
timezone: Europe/Kyiv
country: Україна
region: Івано-Франківська область

usd: 28.40
eur: 33.20

title: Мережа вебсайтів нерухомості
keywords: житло, квартира, будинок, купимо, гараж, продаємо житло, здається житло, продаж житла, оренда, подобово, купити житло, продати, знайти, нерухомість, продамо, земля, продаю, власник, продається, здаю житло, безкоштовне оголошення, мвн
description: База даних квартир, будинків, доступного житла, землі та багато інших об'єктів нерухомого майна, які будуються, продаються або передаються в оренду в Івано-Франківськ області.
name: Регіональна нерухомість
brand: Нерухомість
logo: '/assets/images/logo.svg'

author:
  name: Vasyl&nbsp;Mosiychuk
  website: http://www.vasyl.net
  email: info@vasyl.net
developer:
  name: vasyl.net
  website: http://www.vasyl.net
  email: info@vasyl.net

contact:
  name: Мережа вебсайтів нерухомості в&nbsp;України
  address: 76018, м. Івано-Франківськ, вул.&nbsp;Січових&nbsp;Стрільців,&nbsp;56
  phone_main: 380974949649
  phone_hot: 380974949649
  phone_fax: 380974949649
  phone_sms: 380504949649
  phone_advert: 380504949649
  phone_buy_sell: 380974949649
  phone_add_ads: 380504949649
  phone_submit_ads: 380504949649
  phone_support: 380504949649
  phone_buy: 380974949649
  phone_sell: 380974949649
  email: info@realestate.if.ua
  www: https://www.realestate.if.ua/

markdown: kramdown
kramdown:
  auto_ids: false

collections:
  stabs:
    output: true
  otabs:
    output: true
  owners:
    output: true

defaults:
  - scope:
      path: /*/data/*.json
    values:
      layout: "null"
      sitemap: false
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: /*/news/
      type: "news"
    values:
      layout: "news"
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2

sass:
  style: compressed

compress_html:
  clippings: all
  comments: [""]
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]
